
oc_platform_home:
    path:      /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*
    
oc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id: \d+
    
oc_platform_add:
    path:      /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+
        
oc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+
        
oc_platform_purge:
    path:      /purge/{days}
    defaults:
        _controller: OCPlatformBundle:Advert:purge
    requirements:
        id: \d+

oc_platform_delete_application:
    path:      /deleteApplication/{idAdvert}/{idApplication}
    defaults:
        _controller: OCPlatformBundle:Advert:deleteApplication
    requirements:
        idAdvert: \d+
        idApplication: \d+
        
oc_platform_apply:
    path:     /apply/{id}
    defaults:
        _controler: OCPlatformBundle:Advert:Apply
    requirements:
        id: \d+



oc_platform_gawc:
    path:     /gawc
    defaults:
        _controller: OCPlatformBundle:Advert:getAdvertWithCategories
        
oc_platform_gawa:
    path:     /gawa/{limit}
    defaults:
        _controller: OCPlatformBundle:Advert:getApplicationsWithAdvert
        limit:       3
    requirements:
        limit: \d+




hello_the_world:
    path:     /hello-world
    defaults:
        _controller: OCPlatformBundle:Advert:hello_world 

oc_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults:
        _controller: OCPlatformBundle:Advert:viewSlug
        _format:     html
    # ou
    #defaults: { _controller: OCPlatformBundle:Advert:viewSlug, _format: html }
    requirements:
        year:   \d{4}
        _format: html|xml

test_error:
    path:      /error
    defaults:
        _controller: OCPlatformBundle:Advert:error
        
        
        
        