parameters:
    minLength: 10
    floodTime: 20

services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments: [ "@mailer", '%locale%', '%minLength%' ]
#            - "@mailer"
#            - "%locale%"
#            - '%minLength%'
# '%locale%' définit dans le fichier app/config

    oc_platform.functions:
        class: OC\PlatformBundle\Functions\OCFunctions
        arguments: [ "@doctrine.orm.entity_manager" ]

    oc_platform.test:
        class: OC\PlatformBundle\ServiceTest\OCServiceTest
        
    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments: [ "@mailer" ]

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments: [ "@oc_platform.email.application_mailer" ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oc_platform.purger.advert:
        class: OC\PlatformBundle\Purger\OCPurger
        arguments:  
            - "@doctrine"
            
    oc_platform.validator.antiflood:
        class: OC\PlatformBundle\Validator\AntifloodValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager", '%floodTime%', "@oc_platform_iptime" ]
        tags:
            - { name: validator.constraint_validator, alias: oc_platform_antiflood }
            # C'est avec l'alias qu'on retrouvera le service

    oc_platform_iptime:
        class: OC\PlatformBundle\Service\IPtime
        arguments: [ "@doctrine.orm.entity_manager", '%floodTime%' ]
            
            