<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLikeQueryBuilder($pattern)
	{
		return $this
		->createQueryBuilder('ads')
		->where('ads.name LIKE :pattern')
		->setParameter('pattern', $pattern)
		;
	}

}
