<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\QueryBuilder;	

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository 
{ // ou extends EntityRepository si on ajoute: use \Doctrine\ORM\EntityRepository;

	public function getAdvertWithCategories(array $categoryNames) {
		$qb = $this
			->createQueryBuilder('a')
			->leftJoin('a.categories', 'cat', 'WITH', 'cat.name IN( :categoriesNames )')
			->setParameter('categoriesNames', array_values($categoryNames))
			->addSelect('cat')
		;
		return $qb->getQuery()->getResult();
	}

	public function myFindAll() {
		//Méthode 1 en passant par l'EntityManager 'a' est le raccourci que l'on donne à l'entité du repository.
		$queryBuilder = $this->_em->CreateQueryBuilder()
			->select('a')
			->from($this->_entityName, 'a')
		;
		// Dans un repository, $this->_entityName est le namespace de l'entité gérée
		// Ici, il vaut donc OC\PlatformBundle\Entity\Advert
		
		// Méthode 2 : en passant par le raccourci (recommandée)
		$queryBuilder = $this->createQueryBuilder('a');
		
		$query = $queryBuilder->getQuery(); // On récupère la Query à partir du QueryBuilder
		//return $query->getResult(); // On retourne les résutats à partir de la Query
		// méthode raccourcie:
		return $this
			->createQueryBuilder('a')
			->getQuery()
			->getResult()
		;
	}
	
	public function findLast() {
		$qb = $this->createQueryBuilder('a');
// 		$qb
// 			->select('a')
// 			->
	return $qb->getSingleResult();
	}
	
	public function myFindDQL($id) {
		$query = $this->_em->createQuery("select a from OCPlatformBundle:Advert a where a.id = :id");
		$query->setParameter('id', $id);
		return $query->getSingleResult();
	}

}
