<?php

namespace OC\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLastByIp($ip)
	{
		$qb = $this->createQueryBuilder('a')
		->andWhere('a.ip = :ip')
		->setParameter('ip', $ip)
		->orderBy('a.date', 'desc')
		->setMaxResults(1)
		;
		return $qb->getQuery()->getOneOrNullResult();
	}
	
	public function getApplicationsWithAdvert($limit) {
		$qb = $this
		->createQueryBuilder('a')
		->leftJoin('a.advert', 'adv')
		->addSelect('adv')
		->orderBy('a.date', 'desc')
		->setMaxResults($limit)
		;
		return $qb->getQuery()->getResult();
	}
}
