<?php

namespace OC\PlatformBundle\Repository;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLikeQueryBuilder($pattern)
	{
		return $this
		->createQueryBuilder('c')
		->where('c.name LIKE :pattern')
		->setParameter('pattern', $pattern)
		;
	}
}
